name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC
  workflow_dispatch:     # Allows manual run from GitHub Actions tab

permissions:
  id-token: write
  contents: write
  issues: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  detect-drift:
    name: Detect Infrastructure Drift
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: infra/tf-app
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: infra/tf-app
        run: terraform plan -detailed-exitcode -no-color || echo "exit_code=$?" >> $GITHUB_ENV

      - name: Handle Drift
        run: |
          echo "Exit code: ${{ steps.plan.outcome }}"
          
          if [ "${{ steps.plan.outcome }}" == "success" ]; then
            echo "✅ No drift detected."
            gh issue close $(gh issue list --search "Infrastructure Drift Detected" --state open --json number -q '.[0].number') || true
          else
            echo "⚠️ Drift detected!"
            gh issue create --title "Infrastructure Drift Detected" \
              --body "Drift was detected in the daily plan run. Please investigate and re-align with Terraform configuration." || true
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
